sudo: false
language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
    # - "3.5-dev" # 3.5 development branch
    # - "3.6-dev" # 3.6 development branch
    # - "nightly" # currently points to 3.7-dev
# command to install dependencies
install: 
#  - pip install tox-travis
#  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
  - python setup.py install
# command to run tests
script:
  - make test
  # - coverage erase
  # - python test/test.py --coverage
  # - coverage combine
